{{- range $namespace := .Values.analysisSubjects }}
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: suspicious-exec
  namespace: {{ $namespace }}
spec:
  kprobes:
    - call: sys_execve
      syscall: true
      selectors:
        - matchBinaries:
            - operator: In
              values:
{{- range $.Values.suspiciousNetworkBinaries }}
                - {{ . | quote }}
{{- end }}
          matchActions:
            - action: Post
        - matchBinaries:
            - operator: In
              values:
{{- range $.Values.suspiciousShellBinaries }}
                - {{ . | quote }}
{{- end }}
          matchActions:
            - action: Post
{{- end }}
