if ! psql -tAc "SELECT 1 FROM pg_roles WHERE rolname = '${KEYCLOAK_DATABASE_USERNAME}'" | grep -q 1; then
  psql -c "CREATE ROLE \"${KEYCLOAK_DATABASE_USERNAME}\" LOGIN PASSWORD '${KEYCLOAK_DATABASE_PASSWORD}';"
else
  psql -c "ALTER ROLE \"${KEYCLOAK_DATABASE_USERNAME}\" WITH LOGIN PASSWORD '${KEYCLOAK_DATABASE_PASSWORD}';"
fi

psql -c "GRANT \"${KEYCLOAK_DATABASE_USERNAME}\" TO \"${PGUSER}\";"

if ! psql -tAc "SELECT 1 FROM pg_database WHERE datname = '${KEYCLOAK_DATABASE_NAME}'" | grep -q 1; then
  psql -c "CREATE DATABASE \"${KEYCLOAK_DATABASE_NAME}\" OWNER \"${KEYCLOAK_DATABASE_USERNAME}\";"
else
  psql -c "ALTER DATABASE \"${KEYCLOAK_DATABASE_NAME}\" OWNER TO \"${KEYCLOAK_DATABASE_USERNAME}\";"
fi
